services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8000:8080"

  redis:
    image: redis:7.4.2
    ports:
      - 6379:6379